### ISSUE TITLE
Land spreadsheet for cnrm-esm2-1 does not show-up in the Explorer

### ISSUE THREAD

**Issue by mpmoine** [ES-DOC-INSTITUTIONAL/cnrm-cerfacs#8]
Dear Es-Doc support,

Despite  `"publish": "on"` for  `cnrm-esm2-1` model in `model_publication.json`, the **land spreadsheet**  does not show up in the ES-DOC Explorer. Is there anything wrong  with this spreadsheet?

Thanks,
Marie-Pierre.

**Comment by davidhassell** [comment]
Hi, Everything looks ok to me, by eye. What do you think, @momipsl ?

**Comment by mpmoine** [comment]
The problem is now solved. Land documentation finally poped-up into the Es-Doc search interface. This issue can be closed.
